import 'package:cloud_firestore/cloud_firestore.dart';

class Task {
  String? id; // Made nullable to allow Firestore to generate it
  final String title;
  final String description;
  bool isCompleted;

  Task({
    this.id, // Allow Firestore to set this after adding
    required this.title,
    required this.description,
    this.isCompleted = false, // Default value for isCompleted
  });

  // Method to convert Task to JSON (for saving to Firestore)
  Map<String, dynamic> toJson() {
    return {
      'title': title,
      'description': description,
      'isCompleted': isCompleted,
    };
  }

  // Factory method to create a Task from Firestore DocumentSnapshot
  factory Task.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return Task(
      id: doc.id, // Firestore document ID
      title: data['title'],
      description: data['description'],
      isCompleted: data['isCompleted'] ?? false, // Default to false if not set
    );
  }

  // Factory method to create a Task from JSON (if you need to deserialize from other sources)
  factory Task.fromJson(Map<String, dynamic> json) {
    return Task(
      id: json['id'], // Note: This may be null if generated by Firestore
      title: json['title'],
      description: json['description'],
      isCompleted: json['isCompleted'] ?? false, // Default to false if not set
    );
  }
}
